language: c

os:
  - linux
  - osx

compiler:
  - gcc

#See http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Glbq3TqHAvxEiaxiTyV+pP+1aE+giEV7L5qJzQrUzs8k+XjvvgR6ixI7wezV4520lz8tHcvEakLJd2dD8YLJbjKnSEmamn4oSF0a0/Lvv/eoytHeKMKjN6LHZ/87DgA+gKGskJc4Ai6CYFliCwcqGlGVPmgcKDy9bZn28Csu6o0="

   # Needed for osx builds
   - PKG_CONFIG_PATH: /usr/local/opt/sqlite/lib/pkgconfig

install:
  - |
    case $TRAVIS_OS_NAME in
    osx)
      brew install autoconf-archive
      brew install sqlite
      brew install lcov
      ;;
    esac
    gem install coveralls-lcov

script:
  - ./autogen.sh
  - ./configure --enable-debug --enable-coverage
  - make
  - make install
  - testsuite/startall.sh
  - make check
  - testsuite/killall.sh

after_success:
  - lcov --compat-libtool --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info "/usr/*" --output-file coveralls.info
  - coveralls-lcov coveralls.info

after_script:
  - |
    echo Test Suite log:
    cat tests/test-suite.log
  - |
    echo Hub logs:
    cd ~/ircd
    tail -n +1 \
      logs/ircd.log.1 \
      logs/userlog.1 \
      logs/fuserlog.1 \
      logs/operlog.1 \
      logs/foperlog.1 \
      logs/serverlog.1 \
      logs/klinelog.1 \
      logs/killlog.1 \
      logs/operspylog.1 \
      logs/ioerror.1 \
  - |
    echo Leaf1 logs:
    cd ~/ircd
    tail -n +1 \
      logs/ircd.log.2 \
      logs/userlog.2 \
      logs/fuserlog.2 \
      logs/operlog.2 \
      logs/foperlog.2 \
      logs/serverlog.2 \
      logs/klinelog.2 \
      logs/killlog.2 \
      logs/operspylog.2 \
      logs/ioerror.2 \
  - |
    echo Leaf2 logs:
    cd ~/ircd
    tail -n +1 \
      logs/ircd.log.3 \
      logs/userlog.3 \
      logs/fuserlog.3 \
      logs/operlog.3 \
      logs/foperlog.3 \
      logs/serverlog.3 \
      logs/klinelog.3 \
      logs/killlog.3 \
      logs/operspylog.3 \
      logs/ioerror.3 \



addons:
  apt:
    packages:
      - build-essential
      - autoconf-archive
      - libssl-dev
      - flex
      - bison
      - astyle
      - libsqlite3-dev
      - expect
      - tcl
      - tcllib
      - lcov
  coverity_scan:
    project:
      name: "Elemental-IRCd/elemental-ircd"
    notification_email: xena@yolo-swag.com
    build_command_prepend: ./autogen.sh && ./configure --enable-assert
    build_command: make
    branch_pattern: coverity_scan
