language: c
compiler:
- gcc
- clang

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Glbq3TqHAvxEiaxiTyV+pP+1aE+giEV7L5qJzQrUzs8k+XjvvgR6ixI7wezV4520lz8tHcvEakLJd2dD8YLJbjKnSEmamn4oSF0a0/Lvv/eoytHeKMKjN6LHZ/87DgA+gKGskJc4Ai6CYFliCwcqGlGVPmgcKDy9bZn28Csu6o0="

script:
  - ./configure --enable-assert
  - make
  - make install
  - testsuite/startall.sh
  - make check
  - testsuite/killall.sh

addons:
  apt:
    packages:
      - build-essential
      - libssl-dev
      - flex
      - bison
      - astyle
      - libsqlite3-dev
      - tcl
      - tcllib
  coverity_scan:
    project:
      name: "Elemental-IRCd/elemental-ircd"
      description: "Continuation of ShadowIRCD to meet people's needs"
    notification_email: xena@yolo-swag.com
    build_command_prepend: ./configure --enable-assert
    build_command: make
    branch_pattern: coverity_scan
