language: c
compiler:
- gcc

#See http://docs.travis-ci.com/user/migrating-from-legacy/
#Using legacy infrastructure for now as the test suite needs
#a tcl extension
sudo: true

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Glbq3TqHAvxEiaxiTyV+pP+1aE+giEV7L5qJzQrUzs8k+XjvvgR6ixI7wezV4520lz8tHcvEakLJd2dD8YLJbjKnSEmamn4oSF0a0/Lvv/eoytHeKMKjN6LHZ/87DgA+gKGskJc4Ai6CYFliCwcqGlGVPmgcKDy9bZn28Csu6o0="

before_script:
  - sudo add-apt-repository ppa:ariscop/tcloo -y
  - sudo apt-get update -q
  - sudo apt-get install tcloo

script:
  - ./autogen.sh
  - ./configure --enable-assert
  - make
  - make install
  - cd testsuite
  - ./startall.sh
  - cd ..
  - make check

addons:
  apt:
    packages:
      - build-essential
      - autoconf-archive
      - libssl-dev
      - flex
      - bison
      - astyle
      - libsqlite3-dev
      - expect
      - tcl
  coverity_scan:
    project:
      name: "Elemental-IRCd/elemental-ircd"
      description: "Continuation of ShadowIRCD to meet people's needs"
    notification_email: xena@yolo-swag.com
    build_command_prepend: ./autogen.sh && ./configure --enable-assert
    build_command: make
    branch_pattern: coverity_scan
